# Generated by Django 2.2.11 on 2020-04-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20200402_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='image',
        ),
    ]
