# Generated by Django 2.2.11 on 2020-04-02 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0003_remove_update_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Updates',
        ),
    ]
