# Generated by Django 2.2.11 on 2020-04-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_auto_20200402_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='User',
            new_name='user',
        ),
    ]
