# Generated by Django 2.2.11 on 2020-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200407_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
